# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookReminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookReminder
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'	
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'KakaoSDK', '~> 2.0.0-beta.7'
  pod 'Firebase/Auth'
  pod 'Carte'
  pod 'GoogleSignIn'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-podso
end
  post_install do |installer|
  pods_dir = File.dirname(installer.pods_project.path)
  at_exit { `ruby #{pods_dir}/Carte/Sources/Carte/carte.rb configure` }


end

