# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookReminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookReminder
  pod 'Firebase/Analytics'	
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'KakaoSDK', '~> 2.0.0-beta.7'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'RxDataSources', '~> 4.0'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
end

target 'BookReminderTests' do
  inherit! :search_paths
  pod 'Firebase/Analytics'	
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
end

